/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { SiStorage, SiStorageInterface } from "../SiStorage";

const _abi = [
  {
    inputs: [],
    name: "decrement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "increment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "variable",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101d48061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80632baeceb714610046578063b6854a2114610050578063d09de08a1461006e575b600080fd5b61004e610078565b005b610058610093565b60405161006591906100cd565b60405180910390f35b610076610099565b005b600160008082825461008a9190610117565b92505081905550565b60005481565b60016000808282546100ab919061015a565b92505081905550565b6000819050919050565b6100c7816100b4565b82525050565b60006020820190506100e260008301846100be565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b6000610122826100b4565b915061012d836100b4565b9250828203905081811260008412168282136000851215161715610154576101536100e8565b5b92915050565b6000610165826100b4565b9150610170836100b4565b925082820190508281121560008312168382126000841215161715610198576101976100e8565b5b9291505056fea2646970667358221220cfd2b801a1f33cd1db602ab601bb9abc6e923fbdf26f17beb0a974c78f1a1ee464736f6c634300081c0033";

type SiStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SiStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SiStorage__factory extends ContractFactory {
  constructor(...args: SiStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SiStorage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SiStorage__factory {
    return super.connect(runner) as SiStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SiStorageInterface {
    return new Interface(_abi) as SiStorageInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SiStorage {
    return new Contract(address, _abi, runner) as unknown as SiStorage;
  }
}
