/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as task1Sol from "./Task1.sol";
export type { task1Sol };
export type { Multisend } from "./Multisend";
export * as factories from "./factories";
export { Multisend__factory } from "./factories/Multisend__factory";
export type { SiStorage } from "./Task1.sol/SiStorage";
export { SiStorage__factory } from "./factories/Task1.sol/SiStorage__factory";
